// GENERATED BY BUILD
import Foundation
import SwiftUI
import PolySpatialRealityKit
import UnityFramework

extension UnityPolySpatialApp {
    func initialWindowName() -> String { return "Bounded-0.500x0.500x0.500" }

    func getAllAvailableWindows() -> [String] { return ["Unbounded", "Bounded-0.500x0.500x0.500"] }

    func getAvailableWindowsForMatch() -> [simd_float3] { return [] }

    func displayProviderParameters() -> DisplayProviderParameters { return .init(
            framebufferWidth: 1920,
            framebufferHeight: 1080,
            leftEyePose: .init(position: .init(x: 0, y: 0, z: 0),
                               rotation: .init(x: 0, y: 0, z: 0, w: 1)),
            rightEyePose: .init(position: .init(x: 0, y: 0, z: 0),
                                rotation: .init(x: 0, y: 0, z: 0, w: 1)),
            leftProjectionHalfAngles: .init(left: -1, right: 1, top: 1, bottom: -1),
            rightProjectionHalfAngles: .init(left: -1, right: 1, top: 1, bottom: -1)
        )
    }

    
    @SceneBuilder
    var mainScenePart0: some Scene {

        WindowGroup(id: "Bounded-0.500x0.500x0.500", for: UUID.self) { uuid in
            PolySpatialContentViewWrapper()
                .environment(\.pslWindow, PolySpatialWindow(uuid.wrappedValue, "Bounded-0.500x0.500x0.500", .init(0.500, 0.500, 0.500)))
            KeyboardTextField().frame(width: 0, height: 0).modifier(LifeCycleHandlerModifier())
        } defaultValue: { UUID() } .windowStyle(.volumetric).defaultSize(width: 0.500, height: 0.500, depth: 0.500, in: .meters) 
        ImmersiveSpace(id: "Unbounded", for: UUID.self) { uuid in
            PolySpatialContentViewWrapper()
                .environment(\.pslWindow, PolySpatialWindow(uuid.wrappedValue, "Unbounded", .init(1.000, 1.000, 1.000)))
            KeyboardTextField().frame(width: 0, height: 0).modifier(LifeCycleHandlerModifier())
        } defaultValue: { UUID() }  .upperLimbVisibility(.hidden)
    }

    @SceneBuilder
    var mainScene: some Scene {
        mainScenePart0
    }


    struct LifeCycleHandlerModifier: ViewModifier {
        func body(content: Content) -> some View {
            content
                .onOpenURL(perform: { url in
                    UnityLibrary.instance?.setAbsoluteUrl(url.absoluteString)
                })
        }
    }
}
